/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaLógica.Bingo;
import javax.swing.JOptionPane;

/**
 *
 * @author jerem
 */
public class EleccionPatron extends javax.swing.JFrame {

    private Bingo datos;
    
    public EleccionPatron() {
        initComponents();       
    }
    public EleccionPatron(Bingo data) {
        initComponents();
        //Se trae la data del objeto desde la vista anterior
        datos = data;
        cargarCombo();
    }
    
    //Se llena el combobox con los titulos asignados a los patrones en configuracion
    public void cargarCombo(){
        for(int i = 0; i<3; i++){
            jCboPatrones.addItem(datos.getTitulosPatrones(i));
        }
        jCboPatrones.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboPatrones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBtnComenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione el patrón de juego para comenzar la partida");

        jCboPatrones.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Selección Patrón.jpg"))); // NOI18N

        jBtnComenzar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jBtnComenzar.setText("Comenzar Partida");
        jBtnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jCboPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jBtnComenzar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jCboPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jBtnComenzar)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComenzarActionPerformed
        if(jCboPatrones.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar algún patrón antes de comenzar el juego.", "Advertencia del sistema", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         
        try{
            //Se guarda el patrón con el que se jugará la partida actual
            datos.setPatronSeleccionado(jCboPatrones.getSelectedIndex());
            //Una vez obtenido el patrón a jugar, se calcula la cantidad de posiciones seleccionadas por el usuario para el patrón.
            datos.calcularNumerosPatron();
            
            //Se crea el objeto de la pantalla de juego
            dispose();
            PantallaJuego pantallaJuego = new PantallaJuego(datos);
            pantallaJuego.setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un problema al intentar iniciar el juego.", "Advertencia del sistema", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBtnComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleccionPatron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleccionPatron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleccionPatron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleccionPatron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleccionPatron().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnComenzar;
    private javax.swing.JComboBox<String> jCboPatrones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
